CREATE DATABASE JAVAPROJECT;

USER JAVAPROJECT;

CREATE TABLE Users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  number VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  otp INT,
  otpTime BIGINT
);

select * from Users;